name: CMP

# This is the default format for paths.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title
permalink: /:categories/:title

production_url : http://cmp.ucsf.edu

atom_path: /atom.xml
rss_path: /rss.xml

# Publications are automatically pulled from PubMed
# based on the presence of a CMP faculty name in a pub's author field
pubmed_link : "http://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&amp=&term=((Correia,+Maria+Almira%5BAuthor%5D)+OR+(Fujimori,+Danica+Galonic%5BAuthor%5D)+OR+(Mullins,+Dyche%5BAuthor%5D)+OR+(Bourne,+Henry%5BAuthor%5D)+OR+(Ingraham,+Holly%5BAuthor%5D)+OR+(Taunton,+Jack%5BAuthor%5D)+OR+(Wells,+James%5BAuthor%5D)+OR+(Lansman,+Jeffry%5BAuthor%5D)+OR+(Weissman,+Jonathan%5BAuthor%5D)+OR+(Yamamoto,+Keith%5BAuthor%5D)+OR+(Shokat,+Kevan%5BAuthor%5D)+OR+(Brinen,+Linda%5BAuthor%5D)+OR+(Kruidering-Hall,+Marieke%5BAuthor%5D)+OR+(Krogan,+Nevan%5BAuthor%5D)+OR+(Nicoll,+Roger%5BAuthor%5D)+OR+(Vale,+Ronald%5BAuthor%5D)+OR+(Douglas,+Shawn+M%5BAuthor%5D)+OR+(Masters,+Susan%5BAuthor%5D)+OR+(Lim,+Wendell%5BAuthor%5D))+AND+san+francisco%5BAffiliation%5D"
# PubMed also provides the search results in RSS format
# The proper url for RSS is available from the page set in the previous variable
# ('RSS' link at top right under search box)
# and these two variable should be changed in conjunction
# when the faculty names need to be updated
pubmed_rss : "http://www.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1Zi2AdWYRHLCFrH0oSVyhSQ-LAQ8T2NB8zv8EWIMikIZ_G9E9M"

# Update following https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown
highlighter: rouge

# pagination
paginate: 5
paginate_path: "publications/page:num/index.html"
